transcriptome_fasta_fn: "Araport11_genes.201606.cdna.fasta"
genome_fasta_fn: "Arabidopsis_thaliana.TAIR10.dna.toplevel.fa"
gtf_fn: 'Araport11_GFF3_genes_transposons.201606.no_chr.gtf'

eno_fasta_fn: "../check_contaminants/eno2.fa"

minimap2_parameters:
  junc_bonus: 10

d3pendr_parameters:
  nboots: 999

multicomp:
  - col0_low_vs_col0_high_vs_vir1_low_vs_vir1_high 

comps:
  - vir1_low_vs_col0_low
  - vir1_high_vs_col0_high
  - col0_low_vs_col0_high
  - vir1_low_vs_vir1_high

samples:
  - col0_low_1
  - col0_low_2
  - col0_low_3
  - col0_low_4
  - col0_high_1
  - col0_high_2
  - col0_high_3
  - col0_high_4
  - vir1_low_2
  - vir1_low_3
  - vir1_low_4
  - vir1_high_1
  - vir1_high_2
  - vir1_high_3
  - vir1_high_4

conds:
  - col0_low
  - col0_high
  - vir1_low
  - vir1_high
